# Generated by Django 5.1.1 on 2024-09-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="serial",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
