# Generated by Django 5.1.1 on 2024-09-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_serial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="updated_at",
        ),
    ]
