# Generated by Django 5.1.1 on 2024-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_remove_invoice_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email",
            field=models.EmailField(
                default="imtiazalshariar@gmail.com", max_length=100
            ),
        ),
    ]
