# Generated by Django 5.1.1 on 2024-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_invoice_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="email",
            field=models.EmailField(default="someone@example.com", max_length=100),
        ),
    ]
