# Generated by Django 5.1.1 on 2024-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_invoice_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
