# Generated by Django 5.1.1 on 2024-09-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0008_client_remove_invoice_client_name_invoice_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="email",
        ),
    ]
